# Generated by Django 2.2.7 on 2019-12-10 21:52

import cars.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_auto_20191210_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.Company'),
        ),
        migrations.AlterField(
            model_name='car',
            name='rate',
            field=models.IntegerField(null=True, validators=[cars.models.validate_rate_range]),
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
